### ISSUE TITLE
Top toolbar reverts from image to color when collapsing/expanding a deck

### ISSUE THREAD

**Issue by silverwings15** [lovac42/DancingBaloney#2]
Hi, i'm testing on the latest Baloney version (0.3) with Anki 2.1.22 and no other addon enabled.

at startup
![before](https://i.imgur.com/O9TJ1N3.png)

after collapsing the bottom deck:
![after](https://i.imgur.com/1hxetYR.png)

also the background vanishes for half a second when doing this before reappearing, though i'm not sure if that's a bug or it's simply rechecking/reloading the specified images (which would be redundant imo)

amazing addonn otherwise, thank you for looking into this!

**Comment by lovac42** [comment]
Thanks, this will be fixed in the next release.

Some of the code certainly are redundant, they are put in for cross platform compatibility and for different versions of Anki as the API changes within patch release. You can certainly get more performance if you strip it down for your specific needs. But then you'll have to deal with upgrade nightmares as you move to different machines.
